I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 18, in script
    default config.rollback_enabled = False
  File "game/options.rpy", line 18, in script
    default config.rollback_enabled = False
  File "game/options.rpy", line 18, in execute
    default config.rollback_enabled = False
  File "renpy/common/000namespaces.rpy", line 36, in set_default
    raise Exception("The default statement can not be used with the {} namespace.".format(self.name))
Exception: The default statement can not be used with the config namespace.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Beller\Desktop\Saved Files\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/options.rpy", line 18, in script
    default config.rollback_enabled = False
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/options.rpy", line 18, in script
    default config.rollback_enabled = False
  File "game/options.rpy", line 18, in execute
    default config.rollback_enabled = False
  File "renpy/common/000namespaces.rpy", line 36, in set_default
    raise Exception("The default statement can not be used with the {} namespace.".format(self.name))
Exception: The default statement can not be used with the config namespace.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Imaginary Friends 1.0
Sat Mar 11 11:15:46 2023
